# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Visualize This!
  fr: Faites-nous voir ça!
email: viz-challenge@westgrid.ca
description:
  en: The Visualize This Challenge is a national competition organized by WestGrid, SciNet, and Calcul Québec.
  fr: Faites-nous voir ça est un concours national organisé par WestGrid, SciNet, et Calcul Québec.
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "/visualizeThis" # the subpath of your site, e.g. /blog
url: "https://westgrid.github.io"
twitter_username: computecanada
github_username:  computecanada

# Build settings
markdown: kramdown
